server:
  port: 12000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 49.235.66.54:8848
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    cache: false
    encoding: UTF-8
    #     新版本不支持content-type: text/html，故新写法
    servlet:
      content-type: text/html
  redis:
    host: 119.3.142.255
  session:
    store-type: redis